import {
  RiBuilding4Fill,
  RiCoupon2Fill,
  RiDashboardFill,
  RiNotificationBadgeFill,
  RiWhatsappFill,
} from "react-icons/ri";
import {
  IoMdNotifications,
  IoIosLock,
  IoMdMap,
  IoMdSettings,
  IoMdGlobe,
} from "react-icons/io";
import { FaAmbulance, FaUser, FaUsers } from "react-icons/fa";
import { CgNotes } from "react-icons/cg";
import {
  MdFeedback,
  MdMarkunreadMailbox,
  MdNote,
  MdRecordVoiceOver,
  MdSos,
} from "react-icons/md";
import { TbGridDots, TbNotebook } from "react-icons/tb";
import { GiPoliceBadge } from "react-icons/gi";
import {
  AiFillFolder,
  AiFillInfoCircle,
  AiFillCheckCircle,
} from "react-icons/ai";
import NigerianFlag from "../assets/images/nigeriaflag.png";
import ArgentinaFlag from "../assets/images/argentina-flag-icon.png";
import AustraliaFlag from "../assets/images/australia-flag-icon.png";
import ArubaFlag from "../assets/images/aruba-flag-icon.png";
import BosniaAndHerzegovinaFlag from "../assets/images/bosnia-and-herzegovina-flag-icon.png";
import BangladeshFlag from "../assets/images/bangladesh-flag-icon.png";
import BahrainFlag from "../assets/images/bahrain-flag-icon.png";
import BermudaFlag from "../assets/images/bermuda-flag-icon.png";
import BeninFlag from "../assets/images/benin-flag-icon.png";
import BoliviaFlag from "../assets/images/bolivia-flag-icon.png";
import BrazilFlag from "../assets/images/brazil-flag-icon.png";
import BahamasFlag from "../assets/images/bahamas-flag-icon.png";
import UsersManagement from "../pages/UsersManagement";

// Users Breakdown
export const usersBreakdown = [
  { name: "Total users", value: "200,000" },
  { name: "Verified users", value: "100,000" },
];

// Main NavLinks
export const mainNavlinks = [
  {
    title: "Dashboard",
    icon: <RiDashboardFill />,
    chevron: true,
    type: "navlink",
    path: "/dashboard",
  },
  {
    title: "Notifications",
    icon: <IoMdNotifications />,
    chevron: true,
    type: "navlink",
    path: "/notifications",
  },
  {
    title: "Notices",
    icon: <RiNotificationBadgeFill />,
    chevron: true,
    type: "dropdown",
    list: [
      { title: "Messages", path: "/notices/messages" },
      { title: "Alerts", path: "/notices/alerts" },
    ],
  },
  {
    title: "Access",
    icon: <IoIosLock />,
    chevron: true,
    type: "dropdown",
    list: [
      { title: "Privileges", path: `/access/privileges` },
      { title: "Roles", path: `/access/roles` },
      { title: "Sub-Admin", path: `/access/sub-admin` },
    ],
  },
  {
    title: "Users Management",
    icon: <FaUser />,
    chevron: false,
    type: "navlink",
    path: "/users-management",
    component: <UsersManagement />,
  },
  {
    title: "Promotion Management",
    icon: <CgNotes />,
    chevron: true,
    type: "dropdown",
    list: [
      { title: "Android", path: `/promotion-management/android` },
      { title: "iOS", path: `/promotion-management/ios` },
    ],
  },
  {
    title: "Verification Management",
    icon: <AiFillCheckCircle />,
    chevron: true,
    type: "navlink",
    path: "/verification-management",
  },
  {
    title: "Ambulance Management",
    icon: <FaAmbulance />,
    chevron: true,
    type: "navlink",
    path: "/ambulance-management",
  },
  {
    title: "Emergency Management",
    icon: (
      <div className="p-0.5 bg-white text-black text-[8px] rounded-full">
        <MdSos />
      </div>
    ),
    chevron: true,
    type: "navlink",
    path: "/emergency-management",
  },
  {
    title: "Petition Management",
    icon: <MdNote />,
    chevron: true,
    type: "navlink",
    path: "/petition-management",
  },
  {
    title: "Complaint Management",
    icon: <AiFillFolder />,
    chevron: true,
    type: "navlink",
    path: "/complaint-management",
  },
  {
    title: "iReport Management",
    icon: <MdRecordVoiceOver />,
    chevron: true,
    type: "navlink",
    path: "/ireport-management",
  },
  {
    title: "Travel Safe Management",
    icon: <GiPoliceBadge />,
    chevron: true,
    type: "navlink",
    path: "/travel-safe-management",
  },
  {
    title: "Info Bank Management",
    icon: <AiFillInfoCircle />,
    chevron: true,
    type: "navlink",
    path: "/info-bank-management",
  },
  {
    title: "Top Stories Management",
    icon: <TbNotebook />,
    chevron: true,
    type: "navlink",
    path: "/top-stories-management",
  },
  {
    title: "Suggestion Management",
    icon: <MdMarkunreadMailbox />,
    chevron: true,
    type: "navlink",
    path: "/suggestion-management",
  },
  {
    title: "Feedback Management",
    icon: <MdFeedback />,
    chevron: true,
    type: "navlink",
    path: "/feedback-management",
  },
  {
    title: "Climate Management",
    icon: <IoMdGlobe />,
    chevron: true,
    type: "navlink",
    path: "/climate-management",
  },
  {
    title: "Kaci Code Management",
    icon: <RiCoupon2Fill />,
    chevron: true,
    type: "navlink",
    path: "/kaci-code-management",
  },
];

// More Section links
export const moreNavLinks = [
  {
    title: "Areas",
    icon: <IoMdMap />,
    chevron: true,
    type: "dropdown",
    path: "/more/areas",
    list: [
      { title: "Country", path: `/more/areas/country` },
      { title: "Location", path: `/more/areas/location` },
    ],
  },
  {
    title: "Agencies",
    chevron: true,
    type: "navlink",
    icon: <RiBuilding4Fill />,
    path: "/more/agencies",
  },
  {
    title: "Help Book",
    icon: <FaUsers />,
    chevron: true,
    type: "navlink",
    path: "/more/help-book",
  },
  {
    title: "Complaint Subject",
    icon: <AiFillFolder />,
    chevron: true,
    type: "navlink",
    path: "/more/complaint-subject",
  },
  {
    title: "Ambulance Service",
    icon: <FaAmbulance />,
    chevron: true,
    type: "navlink",
    path: "/more/ambulance-service",
  },
  {
    title: "Keywords",
    icon: <TbGridDots />,
    chevron: true,
    type: "navlink",
    path: "/more/keywords",
  },
  {
    title: "Whatsapp Chat Logs",
    icon: <RiWhatsappFill />,
    chevron: true,
    type: "navlink",
    path: "/more/whatsapp-chat-logs",
  },
  {
    title: "Settings",
    icon: <IoMdSettings />,
    chevron: true,
    type: "navlink",
    path: "/more/settings",
  },
];

// Languages
export const countries = [
  { title: "Nigeria", flag: NigerianFlag },
  { title: "Argentina", flag: ArgentinaFlag },
  { title: "Australia", flag: AustraliaFlag },
  { title: "Aruba", flag: ArubaFlag },
  { title: "Bosnia and Herzegovina", flag: BosniaAndHerzegovinaFlag },
  { title: "Bangladesh", flag: BangladeshFlag },
  { title: "Bahrain", flag: BahrainFlag },
  { title: "Bermuda", flag: BermudaFlag },
  { title: "Benin", flag: BeninFlag },
  { title: "Bolivia, Plurinational...", flag: BoliviaFlag },
  { title: "Brazil", flag: BrazilFlag },
  { title: "Bahamas", flag: BahamasFlag },
];

// Themes
export const theme = {
  yellow: "text-yellow-600 bg-yellow-600/10",
  indigo: "text-indigo-600 bg-indigo-600/10",
  purple: "text-purple-600 bg-purple-600/10",
  violet: "text-violet-600 bg-violet-600/10",
  green: "text-green-600 bg-green-600/10",
  cyan: "text-cyan-600 bg-cyan-600/10",
  sky: "text-sky-600 bg-sky-600/10",
  pink: "text-pink-600 bg-pink-600/10",
  blue: "text-blue-600 bg-blue-600/10",
  lime: "text-lime-600 bg-lime-600/10",
  rose: "text-rose-600 bg-rose-600/10",
  red: "text-red-600 bg-red-600/10",
};

// Total Users
export const users = [
  {
    id: 0,
    "S/N": 6374,
    KSN: 4846387367569,
    "Full Name": "Neil Sims",
    "Email Address": "neil.sims@flowbite.com",
    Password: "13245679,",
    "Phone Number": 3873687368723,
    Gender: "male",
    "Date of Birth": "2000-05-12",
    Age: 20,
    "Blood Group": "A",
    Location: "Wuse, Abuja",
    Country: "Nigeria",
    "Total Ambulances": 10,
    "Total Climate Counts": 5,
    "Total Emissions (KG)": 5,
    "Total iReports": 64,
    "Total TravelSafe": 41,
    "Total Suggestions": 4,
    "Total Feedbacks": 5,
    Status: "Verified",
    moreDetails: {
      "Dependant A": {
        Name: "Neil",
        Email: "neil@gmail.com",
        "Phone Number": 13843868436,
        "Relation Type": "Brother",
      },
      "Dependant B": {
        Name: "Nittin",
        Email: "nittin@gmail.com",
        "Phone Number": 13843868436,
        "Relation Type": "Brother",
      },
      Medications: {
        A: {
          name: "sadlfhys",
          description: "dfygsdoiugyoduygdoygdfi",
          dosage: "2/day",
        },
        B: {
          name: "shsdlkjg",
          description: "dfygsdoiugyoduygdoygdfi",
          dosage: "2/day",
        },
        C: {
          name: "asdirulahfka",
          description: "dfygsdoiugyoduygdoygdfi",
          dosage: "2/day",
        },
        D: {
          name: "ueawsfhlk",
          description: "dfygsdoiugyoduygdoygdfi",
          dosage: "2/day",
        },
      },
      "Location History": [{ date: "12/5/2020", location: "Wuse, Abuja" }],
      "Kaci Code": {
        amount: 46,
        expiryDate: "5/6/2024",
      },
    },
  },
  {
    id: 1,
    "S/N": 6374,
    KSN: 4846387367569,
    "Full Name": "Bonnie Green",
    "Email Address": "bonnie@flowbite.com",
    Password: "13245679,",
    "Phone Number": 3873687368723,
    Gender: "male",
    "Date of Birth": "2000-05-12",
    Age: 20,
    "Blood Group": "A",
    Location: "Wuse, Abuja",
    Country: "Nigeria",
    "Total Ambulances": 10,
    "Total Climate Counts": 5,
    "Total Emissions (KG)": 5,
    "Total iReports": 64,
    "Total TravelSafe": 41,
    "Total Suggestions": 4,
    "Total Feedbacks": 5,
    Status: "Unverified",
    moreDetails: {
      "Dependant A": {
        Name: "Neil",
        Email: "neil@gmail.com",
        "Phone Number": 13843868436,
        "Relation Type": "Brother",
      },
      "Dependant B": {
        Name: "Nittin",
        Email: "nittin@gmail.com",
        "Phone Number": 13843868436,
        "Relation Type": "Brother",
      },
      Medications: {
        A: {
          name: "sadlfhys",
          description: "dfygsdoiugyoduygdoygdfi",
          dosage: "2/day",
        },
        B: {
          name: "shsdlkjg",
          description: "dfygsdoiugyoduygdoygdfi",
          dosage: "2/day",
        },
        C: {
          name: "asdirulahfka",
          description: "dfygsdoiugyoduygdoygdfi",
          dosage: "2/day",
        },
        D: {
          name: "ueawsfhlk",
          description: "dfygsdoiugyoduygdoygdfi",
          dosage: "2/day",
        },
      },
      "Location History": [{ date: "12/5/2020", location: "Wuse, Abuja" }],
      "Kaci Code": {
        amount: 46,
        expiryDate: "5/6/2024",
      },
    },
  },
  {
    id: 2,
    "S/N": 6374,
    KSN: 4846387367569,
    "Full Name": "Jese Leos",
    "Email Address": "jese@flowbite.com",
    Password: "13245679,",
    "Phone Number": 3873687368723,
    Gender: "male",
    "Date of Birth": "2000-05-12",
    Age: 20,
    "Blood Group": "A",
    Location: "Wuse, Abuja",
    Country: "Nigeria",
    "Total Ambulances": 10,
    "Total Climate Counts": 5,
    "Total Emissions (KG)": 5,
    "Total iReports": 64,
    "Total TravelSafe": 41,
    "Total Suggestions": 4,
    "Total Feedbacks": 5,
    Status: "Verified",
    moreDetails: {
      "Dependant A": {
        Name: "Neil",
        Email: "neil@gmail.com",
        "Phone Number": 13843868436,
        "Relation Type": "Brother",
      },
      "Dependant B": {
        Name: "Nittin",
        Email: "nittin@gmail.com",
        "Phone Number": 13843868436,
        "Relation Type": "Brother",
      },
      Medications: {
        A: {
          name: "sadlfhys",
          description: "dfygsdoiugyoduygdoygdfi",
          dosage: "2/day",
        },
        B: {
          name: "shsdlkjg",
          description: "dfygsdoiugyoduygdoygdfi",
          dosage: "2/day",
        },
        C: {
          name: "asdirulahfka",
          description: "dfygsdoiugyoduygdoygdfi",
          dosage: "2/day",
        },
        D: {
          name: "ueawsfhlk",
          description: "dfygsdoiugyoduygdoygdfi",
          dosage: "2/day",
        },
      },
      "Location History": [{ date: "12/5/2020", location: "Wuse, Abuja" }],
      "Kaci Code": {
        amount: 46,
        expiryDate: "5/6/2024",
      },
    },
  },
  {
    id: 3,
    "S/N": 6374,
    KSN: 4846387367569,
    "Full Name": "Thomas Lean",
    "Email Address": "thomes@flowbite.com",
    Password: "13245679,",
    "Phone Number": 3873687368723,
    Gender: "male",
    "Date of Birth": "2000-05-12",
    Age: 20,
    "Blood Group": "A",
    Location: "Wuse, Abuja",
    Country: "Benin",
    "Total Ambulances": 10,
    "Total Climate Counts": 5,
    "Total Emissions (KG)": 5,
    "Total iReports": 64,
    "Total TravelSafe": 41,
    "Total Suggestions": 4,
    "Total Feedbacks": 5,
    Status: "Verified",
    moreDetails: {
      "Dependant A": {
        Name: "Neil",
        Email: "neil@gmail.com",
        "Phone Number": 13843868436,
        "Relation Type": "Brother",
      },
      "Dependant B": {
        Name: "Nittin",
        Email: "nittin@gmail.com",
        "Phone Number": 13843868436,
        "Relation Type": "Brother",
      },
      Medications: {
        A: {
          name: "sadlfhys",
          description: "dfygsdoiugyoduygdoygdfi",
          dosage: "2/day",
        },
        B: {
          name: "shsdlkjg",
          description: "dfygsdoiugyoduygdoygdfi",
          dosage: "2/day",
        },
        C: {
          name: "asdirulahfka",
          description: "dfygsdoiugyoduygdoygdfi",
          dosage: "2/day",
        },
        D: {
          name: "ueawsfhlk",
          description: "dfygsdoiugyoduygdoygdfi",
          dosage: "2/day",
        },
      },
      "Location History": [{ date: "12/5/2020", location: "Wuse, Abuja" }],
      "Kaci Code": {
        amount: 46,
        expiryDate: "5/6/2024",
      },
    },
  },
  {
    id: 4,
    "S/N": 6374,
    KSN: 4846387367569,
    "Full Name": "Leslie Livingston",
    "Email Address": "leslie@flowbite.com",
    Password: "13245679,",
    "Phone Number": 3873687368723,
    Gender: "male",
    "Date of Birth": "2000-05-12",
    Age: 20,
    "Blood Group": "A",
    Location: "Wuse, Abuja",
    Country: "Nigeria",
    "Total Ambulances": 10,
    "Total Climate Counts": 5,
    "Total Emissions (KG)": 5,
    "Total iReports": 64,
    "Total TravelSafe": 41,
    "Total Suggestions": 4,
    "Total Feedbacks": 5,
    Status: "Verified",
    moreDetails: {
      "Dependant A": {
        Name: "Neil",
        Email: "neil@gmail.com",
        "Phone Number": 13843868436,
        "Relation Type": "Brother",
      },
      "Dependant B": {
        Name: "Nittin",
        Email: "nittin@gmail.com",
        "Phone Number": 13843868436,
        "Relation Type": "Brother",
      },
      Medications: {
        A: {
          name: "sadlfhys",
          description: "dfygsdoiugyoduygdoygdfi",
          dosage: "2/day",
        },
        B: {
          name: "shsdlkjg",
          description: "dfygsdoiugyoduygdoygdfi",
          dosage: "2/day",
        },
        C: {
          name: "asdirulahfka",
          description: "dfygsdoiugyoduygdoygdfi",
          dosage: "2/day",
        },
        D: {
          name: "ueawsfhlk",
          description: "dfygsdoiugyoduygdoygdfi",
          dosage: "2/day",
        },
      },
      "Location History": [{ date: "12/5/2020", location: "Wuse, Abuja" }],
      "Kaci Code": {
        amount: 46,
        expiryDate: "5/6/2024",
      },
    },
  },
];

export const locations = [
  "Wuse, Abuja",
  "Wuse, Abuja",
  "Wuse, Abuja",
  "Wuse, Abuja",
  "Wuse, Abuja",
  "Wuse, Abuja",
  "Wuse, Abuja",
  "Wuse, Abuja",
  "Wuse, Abuja",
];

// Petitions
export const petitions = [
  {
    SN: 1,
    id: 0,
    firstName: "Andy",
    lastName: "Andersion",
    email: "Andy@gmail.com",
    userName: "johndoe",
    phone: 9860649709,
    password: "test1234",
    address: "sbchajjzKakzka",
    zipCode: 74900,
    country: "Belgium",
    status: "active",
    createdAt: "2023-02-23 10:20:36",
  },
  {
    SN: 2,
    id: 1,
    firstName: "Andy",
    lastName: "Andersion",
    email: "Andy@gmail.com",
    userName: "johndoe",
    phone: 9860649709,
    password: "test1234",
    address: "sbchajjzKakzka",
    zipCode: 74900,
    country: "Belgium",
    status: "active",
    createdAt: "2023-02-23 10:20:36",
  },
  {
    SN: 3,
    id: 2,
    firstName: "Andy",
    lastName: "Andersion",
    email: "Andy@gmail.com",
    userName: "johndoe",
    phone: 9860649709,
    password: "test1234",
    address: "sbchajjzKakzka",
    zipCode: 74900,
    country: "Belgium",
    status: "active",
    createdAt: "2023-02-23 10:20:36",
  },
  {
    SN: 4,
    id: 3,
    firstName: "Andy",
    lastName: "Andersion",
    email: "Andy@gmail.com",
    userName: "johndoe",
    phone: 9860649709,
    password: "test1234",
    address: "sbchajjzKakzka",
    zipCode: 74900,
    country: "Belgium",
    status: "active",
    createdAt: "2023-02-23 10:20:36",
  },
  {
    SN: 5,
    id: 4,
    firstName: "Andy",
    lastName: "Andersion",
    email: "Andy@gmail.com",
    userName: "johndoe",
    phone: 9860649709,
    password: "test1234",
    address: "sbchajjzKakzka",
    zipCode: 74900,
    country: "Belgium",
    status: "active",
    createdAt: "2023-02-23 10:20:36",
  },
  {
    SN: 6,
    id: 5,
    firstName: "Andy",
    lastName: "Andersion",
    email: "Andy@gmail.com",
    userName: "johndoe",
    phone: 9860649709,
    password: "test1234",
    address: "sbchajjzKakzka",
    zipCode: 74900,
    country: "Belgium",
    status: "active",
    createdAt: "2023-02-23 10:20:36",
  },
  {
    SN: 7,
    id: 6,
    firstName: "Andy",
    lastName: "Andersion",
    email: "Andy@gmail.com",
    userName: "johndoe",
    phone: 9860649709,
    password: "test1234",
    address: "sbchajjzKakzka",
    zipCode: 74900,
    country: "Belgium",
    status: "active",
    createdAt: "2023-02-23 10:20:36",
  },
  {
    SN: 8,
    id: 7,
    firstName: "Andy",
    lastName: "Andersion",
    email: "Andy@gmail.com",
    userName: "johndoe",
    phone: 9860649709,
    password: "test1234",
    address: "sbchajjzKakzka",
    zipCode: 74900,
    country: "Belgium",
    status: "active",
    createdAt: "2023-02-23 10:20:36",
  },
  {
    SN: 9,
    id: 8,
    firstName: "Andy",
    lastName: "Andersion",
    email: "Andy@gmail.com",
    userName: "johndoe",
    phone: 9860649709,
    password: "test1234",
    address: "sbchajjzKakzka",
    zipCode: 74900,
    country: "Belgium",
    status: "active",
    createdAt: "2023-02-23 10:20:36",
  },
  {
    SN: 10,
    id: 9,
    firstName: "Andy",
    lastName: "Andersion",
    email: "Andy@gmail.com",
    userName: "johndoe",
    phone: 9860649709,
    password: "test1234",
    address: "sbchajjzKakzka",
    zipCode: 74900,
    country: "Belgium",
    status: "active",
    createdAt: "2023-02-23 10:20:36",
  },
  {
    SN: 11,
    id: 10,
    firstName: "Andy",
    lastName: "Andersion",
    email: "Andy@gmail.com",
    userName: "johndoe",
    phone: 9860649709,
    password: "test1234",
    address: "sbchajjzKakzka",
    zipCode: 74900,
    country: "Belgium",
    status: "active",
    createdAt: "2023-02-23 10:20:36",
  },
  {
    SN: 12,
    id: 11,
    firstName: "Andy",
    lastName: "Andersion",
    email: "Andy@gmail.com",
    userName: "johndoe",
    phone: 9860649709,
    password: "test1234",
    address: "sbchajjzKakzka",
    zipCode: 74900,
    country: "Belgium",
    status: "active",
    createdAt: "2023-02-23 10:20:36",
  },
  {
    SN: 130,
    id: 120,
    firstName: "Andy",
    lastName: "Andersion",
    email: "Andy@gmail.com",
    userName: "johndoe",
    phone: 9860649709,
    password: "test1234",
    address: "sbchajjzKakzka",
    zipCode: 74900,
    country: "Belgium",
    status: "active",
    createdAt: "2023-02-23 10:20:36",
  },
  {
    SN: 13,
    id: 12,
    firstName: "Andy",
    lastName: "Andersion",
    email: "Andy@gmail.com",
    userName: "johndoe",
    phone: 9860649709,
    password: "test1234",
    address: "sbchajjzKakzka",
    zipCode: 74900,
    country: "Belgium",
    status: "active",
    createdAt: "2023-02-23 10:20:36",
  },
  {
    SN: 14,
    id: 13,
    firstName: "Andy",
    lastName: "Andersion",
    email: "Andy@gmail.com",
    userName: "johndoe",
    phone: 9860649709,
    password: "test1234",
    address: "sbchajjzKakzka",
    zipCode: 74900,
    country: "Belgium",
    status: "active",
    createdAt: "2023-02-23 10:20:36",
  },
  {
    SN: 15,
    id: 14,
    firstName: "Andy",
    lastName: "Andersion",
    email: "Andy@gmail.com",
    userName: "johndoe",
    phone: 9860649709,
    password: "test1234",
    address: "sbchajjzKakzka",
    zipCode: 74900,
    country: "Belgium",
    status: "active",
    createdAt: "2023-02-23 10:20:36",
  },
  {
    SN: 16,
    id: 15,
    firstName: "Andy",
    lastName: "Andersion",
    email: "Andy@gmail.com",
    userName: "johndoe",
    phone: 9860649709,
    password: "test1234",
    address: "sbchajjzKakzka",
    zipCode: 74900,
    country: "Belgium",
    status: "active",
    createdAt: "2023-02-23 10:20:36",
  },
  {
    SN: 17,
    id: 16,
    firstName: "Joe",
    lastName: "Andersion",
    email: "Andy@gmail.com",
    userName: "johndoe",
    phone: 9860649709,
    password: "test1234",
    address: "sbchajjzKakzka",
    zipCode: 74900,
    country: "Belgium",
    status: "active",
    createdAt: "2023-02-23 10:20:36",
  },
  {
    SN: 18,
    id: 17,
    firstName: "Andy",
    lastName: "Andersion",
    email: "Andy@gmail.com",
    userName: "johndoe",
    phone: 9860649709,
    password: "test1234",
    address: "sbchajjzKakzka",
    zipCode: 74900,
    country: "Belgium",
    status: "active",
    createdAt: "2023-02-23 10:20:36",
  },
  {
    SN: 19,
    id: 18,
    firstName: "Andy",
    lastName: "Andersion",
    email: "Andy@gmail.com",
    userName: "johndoe",
    phone: 9860649709,
    password: "test1234",
    address: "sbchajjzKakzka",
    zipCode: 74900,
    country: "Belgium",
    status: "active",
    createdAt: "2023-02-23 10:20:36",
  },
  {
    SN: 20,
    id: 19,
    firstName: "Andy",
    lastName: "Andersion",
    email: "Andy@gmail.com",
    userName: "johndoe",
    phone: 9860649709,
    password: "test1234",
    address: "sbchajjzKakzka",
    zipCode: 74900,
    country: "Belgium",
    status: "active",
    createdAt: "2023-02-23 10:20:36",
  },
];
